name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        version: ["3.10", "3.11"]
    environment: huggingface-access

    name: Test with Python ${{ matrix.version }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade --no-cache-dir -e '.[dev]'
          python -c "import torch; print(torch.__config__.show())"
          cat /proc/cpuinfo
      - name: Log into HuggingFace
        run: |
            huggingface-cli login --token ${{ secrets.HUGGINGFACE_TOKEN }}
      - name: Run tests
        run: |
            pytest -v --cov=aurora --cov-report term-missing
        env:
            HUGGINGFACE_REPO: wbruinsma/aurora
            MKL_CBWR: COMPATIBLE
